### ISSUE TITLE
InvalidTypesException in flink workload operator API implementation

### ISSUE THREAD

**Issue by wangyangjun** [wangyangjun/RealtimeStreamBenchmark#4]
FlinkWorkloadOperator:
public <R> WorkloadOperator<R> flatMap(final FlatMapFunction<T, R> fun) 

org.apache.flink.api.common.functions.InvalidTypesException: The return type of function 'flatMap(FlinkWorkloadOperator.java:81)' could not be determined automatically, due to type erasure. You can give type information hints by using the returns(...) method on the result of the transformation call, or by letting your function implement the 'ResultTypeQueryable' interface.
	at org.apache.flink.streaming.api.datastream.DataStream.getType(DataStream.java:207)
	at org.apache.flink.streaming.api.datastream.DataStream.map(DataStream.java:559)
	at fi.aalto.dmg.frame.FlinkWorkloadOperator.mapToPair(FlinkWorkloadOperator.java:53)
	at fi.aalto.dmg.workloads.WordCount.Process(WordCount.java:40)
	at fi.aalto.dmg.Workload.Start(Workload.java:44)
	at fi.aalto.dmg.BenchStarter.main(BenchStarter.java:69)
	at fi.aalto.dmg.App.main(App.java:20)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:140)
Caused by: org.apache.flink.api.common.functions.InvalidTypesException: Type of TypeVariable 'R' in 'public fi.aalto.dmg.frame.WorkloadOperator fi.aalto.dmg.frame.FlinkWorkloadOperator.flatMap(fi.aalto.dmg.frame.functions.FlatMapFunction)' could not be determined. This is most likely a type erasure problem. The type extraction currently supports types with generic variables only in cases where all variables in the return type can be deduced from the input type(s).
	at org.apache.flink.api.java.typeutils.TypeExtractor.createTypeInfoWithTypeHierarchy(TypeExtractor.java:492)
	at org.apache.flink.api.java.typeutils.TypeExtractor.privateCreateTypeInfo(TypeExtractor.java:378)
	at org.apache.flink.api.java.typeutils.TypeExtractor.getUnaryOperatorReturnType(TypeExtractor.java:278)
	at org.apache.flink.api.java.typeutils.TypeExtractor.getFlatMapReturnTypes(TypeExtractor.java:119)
	at org.apache.flink.streaming.api.datastream.DataStream.flatMap(DataStream.java:583)
	at fi.aalto.dmg.frame.FlinkWorkloadOperator.flatMap(FlinkWorkloadOperator.java:81)
	... 9 more

**Comment by wangyangjun** [comment]
mapVertices API in file
https://github.com/project-flink/flink-graph/blob/master/src/main/java/flink/graphs/Graph.java
http://mail-archives.apache.org/mod_mbox/flink-dev/201411.mbox/%3CCAJZ2dcVV2Ppt-rrHyGKkbYTbw6GH2mNrLVDZsybn9_GtT4SBhg@mail.gmail.com%3E

**Comment by wangyangjun** [comment]
Solution --- return result type

public <R> WorkloadOperator<R> flatMap(final FlatMapFunction<T, R> fun) {
        TypeInformation<R> returnType = TypeExtractor.createTypeInfo(FlatMapFunction.class, fun.getClass(), 1, null, null);
        DataStream<R> newDataStream = dataStream.flatMap(new org.apache.flink.api.common.functions.FlatMapFunction<T, R>() {
            public void flatMap(T t, Collector<R> collector) throws Exception {
                java.lang.Iterable<R> flatResults = fun.flatMap(t);
                for(R r : flatResults){
                    collector.collect(r);
                }
            }
        }).returns(returnType);
        return new FlinkWorkloadOperator<R>(newDataStream);
    }
